import { Temporada } from "../models/Temporada.model";

export const TEMPORADAS: Temporada[] = [
  {
    id: 1,
    year: 2011,
    descripcion: 'La historia comienza con la llegada del rey Robert Baratheon a Invernalia para pedirle a su amigo, Eddard "Ned" Stark, que sea su Mano del Rey tras la muerte de la anterior. Mientras tanto, en el Muro, los hermanos de la Guardia de la Noche protegen Westeros de peligros desconocidos más allá del territorio salvaje. En Essos, Daenerys Targaryen, la última descendiente de una dinastía real derrocada, se casa con Khal Drogo, un líder dothraki, y comienza a buscar su lugar en el mundo. La temporada culmina con la ejecución de Ned Stark, un evento que cambia todo Westeros.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 1,
        id: 1,
        nombre: 'Winter is Coming',
        descripcion: 'Un desertor del Night’s Watch inquieta al Lord Ned Stark; El Rey Robert llega a Winterfell; el exiliado Viserys Targaryen crea una alianza.',
        imagen: 'assets/images/capitulo1.jpg',
        video: 'https://drive.google.com/file/d/1fX9Zj0brg_Js6NHOFdnRs1DU3XhlTe46/preview',
      },
      {
        temporada: 1,
        id: 2,
        nombre: 'The Kingsroad',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1urfX70LdxLEyIYFCgFeFc8mBgiR8T41_/preview',
      },
      {
        temporada: 1,
        id: 3,
        nombre: 'Lord Snow',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1urfX70LdxLEyIYFCgFeFc8mBgiR8T41_/preview',
      },
      {
        temporada: 1,
        id: 4,
        nombre: 'Cripples, Bastards and Broken Things',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1PxkYAdNOTmqPz82PyAIKo1RkICr2R4fz/preview',
      },
      {
        temporada: 1,
        id: 5,
        nombre: 'The Wolf and the Lion',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1-lriGkHPbAD9AgEUVR3KWmkC2U0-NaHd/preview',
      },
      {
        temporada: 1,
        id: 6,
        nombre: 'A Golden Crown',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1m5bynbaz7OwY6XN2xKgMNeK-yVVbhaXc/preview',
      },
      {
        temporada: 1,
        id: 7,
        nombre: 'You Win or You Die',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1AVc4msVhMizUm8WM_kk6rXbiLBxzmVkd/preview',
      },
      {
        temporada: 1,
        id: 8,
        nombre: 'The Pointy End',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1vEm0R58a8iKGVcHu82g_2ziG5wi_gxGc/preview',
      },
      {
        temporada: 1,
        id: 9,
        nombre: 'Baelor',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1JcUF72F6qpWvzQn0DkuO-gjhRAQ9MGEg/preview',
      },
      {
        temporada: 1,
        id: 10,
        nombre: 'Fire and Blood',
        descripcion: 'Capítulo 2: Desarrollo',
        imagen: 'assets/images/capitulo2.jpg',
        video: 'https://drive.google.com/file/d/1CCBd_CmQPSpfBlJu7K07LJf41ltxJVOy/preview',
      },
    ],
  },
  {
    id: 2,
    year: 2012,
    descripcion: 'Con la muerte de Robert Baratheon, estalla la Guerra de los Cinco Reyes. Joffrey Baratheon, Renly Baratheon, Stannis Baratheon, Robb Stark y Balon Greyjoy se disputan el poder. Stannis intenta tomar Desembarco del Rey con la ayuda de la magia de Melisandre, pero es repelido en la Batalla del Aguasnegras gracias a Tyrion Lannister y el fuego valyrio. En Essos, Daenerys lucha por sobrevivir en la ciudad de Qarth mientras intenta recuperar sus dragones.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 2,
        id: 1,
        nombre:'The North Remembers',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'https://drive.google.com/file/d/1fPlgl4sdob6kcgVF2XGumNjAzlr-Nvvd/preview',
      },
      {
        temporada: 2,
        id: 2,
        nombre:'The Night Lands',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1u2IGoRrqvppieJor4JFvFEA0kd8YHdnv/preview',
      },
      {
        temporada: 2,
        id: 3,
        nombre:'What Is Dead May Never Die',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1dgHMM42GSsmiVv3LF6lwpVw3bDV9To3t/preview',
      },
      {
        temporada: 2,
        id: 4,
        nombre:'Garden of bones',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1STc-5oIQ-Bpdcv5vs3-lhVWYrgEuUZx9/preview',
      },
      {
        temporada: 2,
        id: 5,
        nombre:'The Ghost of Harrenhal',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1WC5j1sDfHDUwB2bFm08Fcww4d9WQIiSw/preview',
      },
      {
        temporada: 2,
        id: 6,
        nombre:'The Old Gods and the New',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1ucx1gF5-ZBQpw5wHb5Sd1zYcq2agNSOO/preview',
      },
      {
        temporada: 2,
        id: 7,
        nombre:'A Man Without Honor',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1INRx_3prze35OoxzdTNNqxrtGyBIv6i1/preview',
      },
      {
        temporada: 2,
        id: 8,
        nombre:'The Prince of Winterfell',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1Gap-_fC7Fj2IbD6F55bBRNqMcLzVlW-A/preview',
      },
      {
        temporada: 2,
        id: 9,
        nombre:'Blackwater',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1eTtR-4KB8TrypHb1dx_btVb0hnxlKk6M/preview',
      },
      {
        temporada: 2,
        id: 10,
        nombre:'Valar Morghulis',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'https://drive.google.com/file/d/1aDI6GPm4RIhY5WwCTLDYpgeTPDw4vBhF/preview',
      },
    ],
  },
  {
    id: 3,
    year: 2013,
    descripcion: 'Continúa la Guerra de los Cinco Reyes. Robb Stark toma decisiones que le costarán caro, como romper un pacto matrimonial con los Frey. Esto lleva a la infame Boda Roja, donde Robb, su madre Catelyn, y gran parte de su ejército son asesinados. En el Muro, Jon Snow se infiltra entre los salvajes y forma una conexión con Ygritte. Daenerys comienza a construir un ejército liberando esclavos en Astapor y Yunkai.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 3,
        id: 1,
        nombre:'Valar Dohaeris',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'assets/videos/capitulo1_t2.mp4',
      },
      {
        temporada: 3,
        id: 2,
        nombre:'Dark Wings, Dark Words',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 3,
        nombre:'Walk of Punishment',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 4,
        nombre:'And Now His Watch Is Ended',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 5,
        nombre:'Kissed by Fire',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 6,
        nombre:'The Climb',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 7,
        nombre:'The Bear and the Maiden Fair',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 8,
        nombre:'Second Sons',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 9,
        nombre:'The Rains of Castamere',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 3,
        id: 10,
        nombre:'Mhysa',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      }
      
    ],
  },
  {
    id: 4,
    year: 2014,
    descripcion: 'Joffrey muere en su boda tras ser envenenado, un evento conocido como la Boda Púrpura. Tyrion es acusado del asesinato y enfrenta un juicio lleno de intrigas. Mientras tanto, Bran Stark se dirige más allá del Muro para buscar al Cuervo de Tres Ojos. En el Norte, los salvajes atacan el Muro, pero la Guardia de la Noche logra defenderse en la Batalla del Castillo Negro. Daenerys continúa consolidando su poder en Meereen.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 4,
        id: 1,
        nombre:'Two Swords',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'assets/videos/capitulo1_t2.mp4',
      },
      {
        temporada: 4,
        id: 2,
        nombre:'The Lion and the Rose',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 3,
        nombre:'Breaker of Chains',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 4,
        nombre:'Oathkeeper',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 5,
        nombre:'First of His Name',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 6,
        nombre:'The Laws of Gods and Men',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 7,
        nombre:'Mockingbird',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 8,
        nombre:'The Mountain and the Viper',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 9,
        nombre:'The Watchers on the Wall',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 4,
        id: 10,
        nombre:'The Children',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },

    ],
  },
  {
    id: 5,
    year: 2015,
    descripcion: 'Cersei Lannister enfrenta una humillación pública tras caer en manos del Gorrión Supremo. Jon Snow es nombrado Lord Comandante de la Guardia de la Noche y toma decisiones polémicas, como aliarse con los salvajes. Stannis intenta marchar sobre Invernalia, pero fracasa. Arya Stark entrena con los Hombres sin Rostro en Braavos. En Essos, Daenerys enfrenta rebeliones internas en Meereen y conoce a Tyrion. La temporada termina con Jon Snow siendo traicionado y asesinado por sus propios hombres.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 5,
        id: 1,
        nombre:'The Wars to Come',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'assets/videos/capitulo1_t2.mp4',
      },
      {
        temporada: 5,
        id: 2,
        nombre:'The House of Black and White',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 3,
        nombre:'High Sparrow',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 4,
        nombre:'Sons of the Harpy',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 5,
        nombre:'Kill the Boy',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 6,
        nombre:'Unbowed, Unbent, Unbroken',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 7,
        nombre:'The Gift',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 8,
        nombre:'Hardhome',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 9,
        nombre:'The Dance of Dragons',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 5,
        id: 10,
        nombre:'Mothers Mercy',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
    ],
  },
  {
    id: 6,
    year: 2016,
    descripcion: 'Jon Snow es resucitado por Melisandre y lidera a los Stark para recuperar Invernalia en la épica Batalla de los Bastardos, derrotando a Ramsay Bolton. Bran descubre a través de visiones que Jon no es un Stark, sino el hijo de Lyanna Stark y Rhaegar Targaryen. En Desembarco del Rey, Cersei destruye el Septo de Baelor con fuego valyrio, eliminando a sus enemigos, incluida Margaery Tyrell. Daenerys zarpa hacia Westeros con su ejército y sus dragones.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 6,
        id: 1,
        nombre:'The Red Woman',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'assets/videos/capitulo1_t2.mp4',
      },
      {
        temporada: 6,
        id: 2,
        nombre:'Home',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 3,
        nombre:'Oathbreaker',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 4,
        nombre:'Book of the Stranger',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 5,
        nombre:'The Door',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 6,
        nombre:'Blood of My Blood',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 7,
        nombre:'The Broken Man',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 8,
        nombre:'No One',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 9,
        nombre:'Battle of the Bastards',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 6,
        id: 10,
        nombre:'The Winds of Winter',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
    ],
  },
  {
    id: 7,
    year: 2017,
    descripcion: 'Daenerys llega a Rocadragón y forma una alianza con Jon Snow mientras lucha contra los Lannister. Jon intenta convencer a los reinos de unirse contra el Rey de la Noche, líder de los Caminantes Blancos, que avanza hacia el sur con un ejército de muertos. Los Caminantes logran matar a uno de los dragones de Daenerys y lo reviven como un espectro. La temporada termina con el Muro siendo destruido por este dragón no-muerto.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 7,
        id: 1,
        nombre:'Dragonstone',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'assets/videos/capitulo1_t2.mp4',
      },
      {
        temporada: 7,
        id: 2,
        nombre:'Stormborn',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 7,
        id: 3,
        nombre:'The Queen\'s Justice',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 7,
        id: 4,
        nombre:'The Spoils of War',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 7,
        id: 5,
        nombre:'Eastwatch',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 7,
        id: 6,
        nombre:'Beyond the Wall',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 7,
        id: 7,
        nombre:'The Dragon and the Wolf',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
    ],
  },
  {
    id: 8,
    year: 2019,
    descripcion: 'La última temporada comienza con la batalla contra los Caminantes Blancos en Invernalia, donde Arya Stark mata al Rey de la Noche. Después de esta victoria, Daenerys, Jon y sus aliados marchan hacia Desembarco del Rey para enfrentarse a Cersei. Daenerys, consumida por su deseo de poder, destruye la ciudad con Drogon, matando a miles de inocentes. Jon la asesina para evitar que se convierta en una tirana. La serie concluye con Bran Stark siendo elegido rey de los Siete Reinos, aunque el Norte se convierte en un reino independiente bajo Sansa Stark.',
    imagen: 'banner.jpg',
    capitulos: [
      {
        temporada: 8,
        id: 1,
        nombre:'Winterfell',
        descripcion: 'Capítulo 1: Reencuentro',
        imagen: 'assets/images/capitulo1_t2.jpg',
        video: 'assets/videos/capitulo1_t2.mp4',
      },
      {
        temporada: 8,
        id: 2,
        nombre:'A Knight of the Seven Kingdoms',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 8,
        id: 3,
        nombre:'The Long Night',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 8,
        id: 4,
        nombre:'The Last of the Starks',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 8,
        id: 5,
        nombre:'The Bells',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
      {
        temporada: 8,
        id: 6,
        nombre:'The Iron Throne',
        descripcion: 'Capítulo 2: Conflicto',
        imagen: 'assets/images/capitulo2_t2.jpg',
        video: 'assets/videos/capitulo2_t2.mp4',
      },
    ],
  },
];

